/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.34.2.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./UnstakeDelegate.types";
import * as _1 from "./UnstakeDelegate.msg-builder";
import * as _2 from "./UnstakeController.types";
import * as _3 from "./UnstakeController.msg-builder";
import * as _4 from "./UnstakeReserve.types";
import * as _5 from "./UnstakeReserve.msg-builder";
export namespace contracts {
  export const UnstakeDelegate = { ..._0,
    ..._1
  };
  export const UnstakeController = { ..._2,
    ..._3
  };
  export const UnstakeReserve = { ..._4,
    ..._5
  };
}