/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.34.2.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Adapter = {
  eris: Eris;
} | {
  gravedigger: Gravedigger;
} | {
  quark: Quark;
};
export type Eris = string;
export type Gravedigger = string;
export type Addr = string;
export type Decimal = string;
export interface InstantiateMsg {
  adapter: Adapter;
  ask_denom: string;
  delegate_code_id: number;
  min_rate: Decimal;
  offer_denom: string;
  owner: Addr;
  protocol_fee: Decimal;
  protocol_fee_address: Addr;
  reserve_address: Addr;
  unbonding_duration: number;
  vault_address: Addr;
}
export interface Quark {
  hub: Addr;
  liq: Addr;
}
export type ExecuteMsg = {
  unstake: {
    callback?: CallbackData | null;
    max_fee: Uint128;
  };
} | {
  callback: CallbackMsg;
} | {
  complete: {
    offer: Offer;
  };
} | {
  update_config: {
    delegate_code_id?: number | null;
    owner?: Addr | null;
    protocol_fee?: Decimal | null;
    protocol_fee_address?: Addr | null;
  };
} | {
  update_broker: {
    duration?: number | null;
    min_rate?: Decimal | null;
  };
};
export type CallbackData = string;
export type Uint128 = string;
export type CallbackData1 = string;
export type Binary = string;
export interface CallbackMsg {
  callback: CallbackData1;
  data: Binary;
}
export interface Offer {
  fee: Uint128;
  offer_amount: Uint128;
  reserve_allocation: Uint128;
  unbond_amount: Uint128;
}
export type QueryMsg = {
  offer: {
    amount: Uint128;
  };
} | {
  delegates: {};
} | {
  rates: {};
} | {
  status: {};
} | {
  config: {};
};
export interface ConfigResponse {
  adapter: Adapter;
  ask_denom: string;
  debt_denom: string;
  delegate_code_id: number;
  ghost_denom: string;
  offer_denom: string;
  owner: Addr;
  protocol_fee: Decimal;
  protocol_fee_address: Addr;
  reserve_address: Addr;
  vault_address: Addr;
}
export type Timestamp = Uint64;
export type Uint64 = string;
export interface DelegatesResponse {
  delegates: [Addr, Timestamp][];
}
export interface OfferResponse {
  amount: Uint128;
  fee: Uint128;
}
export interface RatesResponse {
  provider_redemption: Decimal;
  vault_debt: Decimal;
  vault_interest: Decimal;
  vault_max_interest: Decimal;
}
export interface StatusResponse {
  total_base: Uint128;
  total_quote: Uint128;
}