/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.34.2.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Adapter = {
  eris: Eris;
} | {
  gravedigger: Gravedigger;
} | {
  quark: Quark;
};
export type Eris = string;
export type Gravedigger = string;
export type Addr = string;
export type Uint128 = string;
export interface InstantiateMsg {
  adapter: Adapter;
  controller: Addr;
  offer: Offer;
  unbond_amount: CheckedCoinForAsk;
}
export interface Quark {
  hub: Addr;
  liq: Addr;
}
export interface Offer {
  fee: Uint128;
  offer_amount: Uint128;
  reserve_allocation: Uint128;
  unbond_amount: Uint128;
}
export interface CheckedCoinForAsk {
  amount: Uint128;
  denom: string;
  [k: string]: unknown;
}
export type ExecuteMsg = {
  complete: {};
} | {
  callback: {};
};
export type QueryMsg = string;