/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.34.2.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { Addr, InstantiateMsg, ExecuteMsg, CallbackData, CallbackData1, CallbackData2, Uint128, CallbackData3, Decimal, QueryMsg, ConfigResponse, StatusResponse, WhitelistResponse, WhitelistItem } from "./UnstakeReserve.types";
import { CamelCasedProperties } from "type-fest";
export abstract class UnstakeReserveExecuteMsgBuilder {
  static fund = ({
    callback
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    fund: unknown;
  }>["fund"]>): ExecuteMsg => {
    return {
      fund: ({
        callback
      } as const)
    };
  };
  static withdraw = ({
    callback
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    withdraw: unknown;
  }>["withdraw"]>): ExecuteMsg => {
    return {
      withdraw: ({
        callback
      } as const)
    };
  };
  static requestReserves = ({
    callback,
    requestedAmount
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    request_reserves: unknown;
  }>["request_reserves"]>): ExecuteMsg => {
    return {
      request_reserves: ({
        callback,
        requested_amount: requestedAmount
      } as const)
    };
  };
  static returnReserves = ({
    callback,
    originalAmount
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    return_reserves: unknown;
  }>["return_reserves"]>): ExecuteMsg => {
    return {
      return_reserves: ({
        callback,
        original_amount: originalAmount
      } as const)
    };
  };
  static addController = ({
    controller,
    limit
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    add_controller: unknown;
  }>["add_controller"]>): ExecuteMsg => {
    return {
      add_controller: ({
        controller,
        limit
      } as const)
    };
  };
  static removeController = ({
    controller
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    remove_controller: unknown;
  }>["remove_controller"]>): ExecuteMsg => {
    return {
      remove_controller: ({
        controller
      } as const)
    };
  };
  static updateConfig = ({
    owner
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    update_config: unknown;
  }>["update_config"]>): ExecuteMsg => {
    return {
      update_config: ({
        owner
      } as const)
    };
  };
  static migrateLegacyReserve = ({
    legacyDenom,
    legacyRedemptionRate,
    reservesDeployed
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    migrate_legacy_reserve: unknown;
  }>["migrate_legacy_reserve"]>): ExecuteMsg => {
    return {
      migrate_legacy_reserve: ({
        legacy_denom: legacyDenom,
        legacy_redemption_rate: legacyRedemptionRate,
        reserves_deployed: reservesDeployed
      } as const)
    };
  };
  static exchangeLegacyReserve = (): ExecuteMsg => {
    return {
      exchange_legacy_reserve: ({} as const)
    };
  };
}
export abstract class UnstakeReserveQueryMsgBuilder {
  static status = (): QueryMsg => {
    return {
      status: ({} as const)
    };
  };
  static whitelist = (): QueryMsg => {
    return {
      whitelist: ({} as const)
    };
  };
  static config = (): QueryMsg => {
    return {
      config: ({} as const)
    };
  };
}