/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.34.2.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { Adapter, Eris, Gravedigger, Addr, Uint128, InstantiateMsg, Quark, Offer, CheckedCoinForAsk, ExecuteMsg, QueryMsg } from "./UnstakeDelegate.types";
import { CamelCasedProperties } from "type-fest";
export abstract class UnstakeDelegateExecuteMsgBuilder {
  static complete = (): ExecuteMsg => {
    return {
      complete: ({} as const)
    };
  };
  static callback = (): ExecuteMsg => {
    return {
      callback: ({} as const)
    };
  };
}