/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.34.2.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Addr = string;
export interface InstantiateMsg {
  base_denom: string;
  ghost_vault_addr: Addr;
  owner: Addr;
}
export type ExecuteMsg = {
  fund: {
    callback?: CallbackData | null;
  };
} | {
  withdraw: {
    callback?: CallbackData1 | null;
  };
} | {
  request_reserves: {
    callback?: CallbackData2 | null;
    requested_amount: Uint128;
  };
} | {
  return_reserves: {
    callback?: CallbackData3 | null;
    original_amount: Uint128;
  };
} | {
  add_controller: {
    controller: Addr;
    limit?: Uint128 | null;
  };
} | {
  remove_controller: {
    controller: Addr;
  };
} | {
  update_config: {
    owner?: Addr | null;
  };
} | {
  migrate_legacy_reserve: {
    legacy_denom: string;
    legacy_redemption_rate: Decimal;
    reserves_deployed: Uint128;
  };
} | {
  exchange_legacy_reserve: {};
};
export type CallbackData = string;
export type CallbackData1 = string;
export type CallbackData2 = string;
export type Uint128 = string;
export type CallbackData3 = string;
export type Decimal = string;
export type QueryMsg = {
  status: {};
} | {
  whitelist: {};
} | {
  config: {};
};
export interface ConfigResponse {
  base_denom: string;
  ghost_denom: string;
  ghost_vault_addr: Addr;
  owner: Addr;
  rsv_denom: string;
}
export interface StatusResponse {
  available: Uint128;
  deployed: Uint128;
  reserve_redemption_rate: Decimal;
  total: Uint128;
}
export interface WhitelistResponse {
  controllers: WhitelistItem[];
}
export interface WhitelistItem {
  controller: Addr;
  lent: Uint128;
  limit?: Uint128 | null;
}